### ISSUE TITLE
preprocessing methods for Xenium and Visium datasets

### ISSUE THREAD

**Issue by guoyang-github** [gao-lab/SLAT#11]
Thanks for your excellent tool!
I noticed that in your tutorial available at https://slat.readthedocs.io/en/latest/tutorials/cross_technology.html, we need Xenium.h5ad and Visium.h5ad for the cross technology alignment.
I wonder what is the pre-processing method from raw data to h5ad for Xenium and Visium?
Thanks.

**Comment by xiachenrui** [comment]
Hi, thanks for your interests !

We followed the common single cell pre-process pipeline in [`Scanpy`](https://scanpy.readthedocs.io/en/stable/tutorials/basics/clustering-2017.html). Please note we used shared genes of Xenium and Visium dataset.

Best,
Chen-Rui
