### ISSUE TITLE
Problems with the spatial_match function in tutorials

### ISSUE THREAD

**Issue by Briskzxm** [gao-lab/SLAT#12]
Hi， @xiachenrui，excellent work！

While reproducing the ‘Basic Usage of SLAT’ and ‘Aligning Across Technologies’ sections of the Readthedocs tutorial, I noticed that the input to the spatial_match function is only the DPCA-processed de-batched embedding (**features**) that have been processed by DPCA. 

This does not seem to match the paper's reference to using cell embedding $Z$. If I'm misunderstanding this, I'm very sorry to bother you and would kindly ask you to clarify this issue. 

Thanks!

**Comment by xiachenrui** [comment]
Thanks for your interesting! @Briskzxm 

It is an error, I will fix it soon.

Best,
Chen-Rui
