### ISSUE TITLE
Stereo sampling issue

### ISSUE THREAD

**Issue by COMPLEXI1** [gao-lab/SLAT#13]
Hello, regarding the tutorial https://slat.readthedocs.io/en/latest/tutorials/times_series.html, the dataset "stereo" used in your work has undergone down-sampling. However, upon checking your code in Stereo_process.ipynb and from scSLAT.utils import norm_to_raw, I did not find any content related to down-sampling. These contents seem to only include data preprocessing. Could you provide the down-sampling code and specify when the down-sampling is performed? Is it conducted before or after data preprocessing?

Thank you.

**Comment by xiachenrui** [comment]
Hi @COMPLEXI1,

Thanks for your interest. We down-sampled the dataset for demonstration only, via

```python
N = int(1e4)
adata = adata[np.random.choice(range(adata.n_obs), N), :].copy()
```

This code is conducted before any preprocess and not included in the tutorial.

Best!
