### ISSUE TITLE
Multi Modality Datasets

### ISSUE THREAD

**Issue by DruncBread** [gao-lab/SLAT#14]
Hi,
I'd like to reproduce the results in your **Spatial-ATAC-seq and Stereo-seq data alignment** experiment

I noticed there are many h5ad files in the Stereo-seq data website https://db.cngb.org/stomics/mosta/download/.
Could you tell me exactly which file you used in your experiment?

And it would be nice if you could also provide the processed Spatial-ATAC-seq data "seurat_peaks.csv" because I had trouble running ArchR on my machine. Thank you!

Best regards

**Comment by xiachenrui** [comment]
Hi @DruncBread,

Thanks for your interests ! We use the [E11.5_E1S1.MOSTA.h5ad](https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000058/stomics/E11.5_E1S1.MOSTA.h5ad).

The raw "seurat_peaks.csv" in paper is not saved but I regenerate it with a higher version ArchR. I hope it can help you. ([Link](https://drive.google.com/file/d/1YM-WRsc3Y_GFhC3D-qcT0K6smd8dx1VR/view?usp=sharing))

Best !
