### ISSUE TITLE
Input of spatial_match()

### ISSUE THREAD

**Issue by DruncBread** [gao-lab/SLAT#15]
Hi,
I noticed in your tutorial that sometimes the input of spatial_match is not the embd0 and embd1 ( the output of method run_SLAT() ).

In some tutorial  like 'Time Series' https://slat.readthedocs.io/en/latest/tutorials/times_series.html
You use the embd0 and embd1 for alignment.
`best, index, distance = spatial_match([embd0, embd1], reorder=False, adatas=[adata1,adata2])`

But in some other tutorials like 'Basic Usage' https://slat.readthedocs.io/en/latest/tutorials/basic_usage.html
You use the graph features for alignment
`best, index, distance = spatial_match(features, adatas=[adata1,adata2], reorder=False)`

It seems that using embeddings from the trained model makes sense, but why do you use the graph features for alignment?
Isn't that makes the run_SLAT() step redundant?
Would you mind explaining this to me? 
Thank you!

Best regards.

**Comment by xiachenrui** [comment]
Hi @DruncBread 

Thanks for your interests ! This is a typo in 'Basic Usage'. We should use embedding from SLAT. Also see #12
