### ISSUE TITLE
A problem about the dataset in Tutorials.

### ISSUE THREAD

**Issue by CocoGzh** [gao-lab/SLAT#5]
Considering that the preprocessing method might lead to inconsistent results, could the author upload the h5ad file to the cloud storage?

**Comment by xiachenrui** [comment]
We had uploaded the processed .h5ad files of our tutorial to cloud drive. Please check https://slat.readthedocs.io/en/latest/tutorials/basic_usage.html.

**Comment by CocoGzh** [comment]
> We had uploaded the processed .h5ad files of our tutorial to cloud drive. Please check https://slat.readthedocs.io/en/latest/tutorials/basic_usage.html.

Thank you!  Is it possible for authors to upload all datasets in https://slat.readthedocs.io/en/latest/data.html to cloud? 
Alternatively, could authors upload dataset in each typical application? For instance, consider the cross-technology cloud uploads described in this tutorial (https://slat.readthedocs.io/en/latest/tutorials/cross_technology.html).

**Comment by xiachenrui** [comment]
Ye. it is totally possible ! I plan to achieve this goal in the coming month.

**Comment by XiHuYan** [comment]
Hi, these processed .h5ad files are available now?

**Comment by xiachenrui** [comment]
@CocoGzh @XiHuYan 
Sorry for delay. 
The processed h5ad files for 
1. xenium ([link](https://drive.google.com/file/d/1-xQSVKHEwVosFasV1urJNwHu70x6me6J/view?usp=drive_link)) and visium ([link](https://drive.google.com/file/d/1DKeEcOf2ovSslciaNBsNMTlbrCrkJ60R/view?usp=drive_link)) in https://slat.readthedocs.io/en/latest/tutorials/cross_technology.html 
2.  E11.5 mouse embryo stereo-seq dataset ([link](https://drive.google.com/uc?export=download&id=1KkuJt6aSlKS1AJzFZjE_odypY-GINRuD)) and E12.5 mouse embryo stereo-seq dataset ([link](https://drive.google.com/uc?export=download&id=1YIiEmjGfHxcDbGn4nv2kzmTHUo3_q5hJ)) in https://slat.readthedocs.io/en/latest/tutorials/times_series.html

were uploaded.
