### ISSUE TITLE
Examples about spatialRNA-ATAC-seq integration 

### ISSUE THREAD

**Issue by huoyuying** [gao-lab/SLAT#7]
Hello! Where is the example of spatial transcriptome and ATAC integration? I didn't find this part in your tutorial. Thank you for your help.

**Comment by xiachenrui** [comment]
Thanks for your interest ! The jupyter notebooks are [here](https://github.com/gao-lab/SLAT/tree/main/case/sptatial_multi-omics). Your may need to install other dependencies [ArchR](https://www.archrproject.com/)  and [scGLUE](https://github.com/gao-lab/GLUE) manually.
