### ISSUE TITLE
Request for Additional Preprocessed Datasets

### ISSUE THREAD

**Issue by wrab12** [gao-lab/SLAT#8]
Excellent work! I noticed that in your tutorial available at [https://slat.readthedocs.io/en/latest/tutorials/basic_usage.html], you provided two preprocessed datasets. Could you please provide additional preprocessed datasets?
Thank you for your assistance.

**Comment by xiachenrui** [comment]
Sure, which dataset do you want ?

**Comment by bbchond** [comment]
> Sure, which dataset do you want ?

Hi, @xiachenrui, Sorry that I am confused about the preprocessing of the Spatial-ATAC-seq and Stereo-seq data used in the multimodal alignment (Section '**Matching heterogeneous datasets across distinct technologies and modalities**') of your paper. Could you please provide the processed data?

I would greatly appreciate any help you can provide, and thank you in advance for your time and assistance.

**Comment by xiachenrui** [comment]
Sure, please leave your email adress and I will send them to you.

**Comment by xkmaxidian** [comment]
> Sure, please leave your email adress and I will send them to you.
Thank you very much for your reply, and my email address is: [yuwangxdu@163.com](mailto:yuwangxdu@163.com).

**Comment by bbchond** [comment]
> Sure, please leave your email adress and I will send them to you.

Thank you very much for your reply, and my email address is: [yuwangxdu@163.com](mailto:yuwangxdu@163.com).

**Comment by YupengXu1** [comment]
Hi, @xiachenrui ,I am also very confused about the preprocessing of the Spatial-ATAC-seq and Stereo-seq data used in the multimodal alignment mentioned above. Could you please also send me a copy of the processed data? My email address is 18879446585@163.com. If you could send the data to me, I would be extremely grateful.

**Comment by ouweihao** [comment]
Hi, @xiachenrui, I has noticed that there exits some preprocessed DLPFC data in this project, Could you please send my these data or just tell me how to process this data. My email address is owenfate@gmail.com.  I appreciate your time and any help you can offer.

**Comment by xiachenrui** [comment]
> Hi, @xiachenrui, I has noticed that there exits some preprocessed DLPFC data in this project, Could you please send my these data or just tell me how to process this data. My email address is [owenfate@gmail.com](mailto:owenfate@gmail.com). I appreciate your time and any help you can offer.

Hi @ouweihao,

Thanks for your interests ! Our paper and GitHub repo contain the URL of the original data and notbooks which record detailed data preprocessing step , so you can easily repeat my preprocessing process. Given the volume of the spatial omics data, I cannot easily share the them via GitHub or e-mail directly.

Best.
